name: twd_hub
description: "The Walking Dead"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.2.1
  provider: ^6.1.5+1
  responsive_framework: ^1.5.1
  flutter_svg: ^2.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
  - family: JollyLodger
    fonts:
      - asset: assets/fonts/JollyLodger-Regular.ttf
