"""add cascade delete to appearance

Revision ID: 2154b81807c9
Revises: 687aedad9d5c
Create Date: 2026-04-15 11:32:47.097641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2154b81807c9'
down_revision: Union[str, Sequence[str], None] = '687aedad9d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appearances_entityid_fkey'), 'appearances', type_='foreignkey')
    op.drop_constraint(op.f('appearances_episodeid_fkey'), 'appearances', type_='foreignkey')
    op.create_foreign_key(op.f('appearances_entityid_fkey'), 'appearances', 'entities', ['entityid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appearances_episodeid_fkey'), 'appearances', 'episodes', ['episodeid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appearances_episodeid_fkey'), 'appearances', type_='foreignkey')
    op.drop_constraint(op.f('appearances_entityid_fkey'), 'appearances', type_='foreignkey')
    op.create_foreign_key(op.f('appearances_episodeid_fkey'), 'appearances', 'episodes', ['episodeid'], ['id'])
    op.create_foreign_key(op.f('appearances_entityid_fkey'), 'appearances', 'entities', ['entityid'], ['id'])
    # ### end Alembic commands ###
