"""add indices and relationships

Revision ID: 687aedad9d5c
Revises: 02fbf71c7055
Create Date: 2026-04-14 22:09:44.294706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687aedad9d5c'
down_revision: Union[str, Sequence[str], None] = '02fbf71c7055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appearanceforms_appearanceid'), 'appearanceforms', ['appearanceid'], unique=False)
    op.drop_constraint(op.f('appearanceforms_appearanceid_fkey'), 'appearanceforms', type_='foreignkey')
    op.create_foreign_key(op.f('appearanceforms_appearanceid_fkey'), 'appearanceforms', 'appearances', ['appearanceid'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_appearances_episodeid_entityid'), 'appearances', ['episodeid', 'entityid'])
    op.create_unique_constraint(op.f('uq_entities_wikihref'), 'entities', ['wikihref'])
    op.create_unique_constraint(op.f('uq_episodes_wikihref'), 'episodes', ['wikihref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_episodes_wikihref'), 'episodes', type_='unique')
    op.drop_constraint(op.f('uq_entities_wikihref'), 'entities', type_='unique')
    op.drop_constraint(op.f('uq_appearances_episodeid_entityid'), 'appearances', type_='unique')
    op.drop_constraint(op.f('appearanceforms_appearanceid_fkey'), 'appearanceforms', type_='foreignkey')
    op.create_foreign_key(op.f('appearanceforms_appearanceid_fkey'), 'appearanceforms', 'appearances', ['appearanceid'], ['id'])
    op.drop_index(op.f('ix_appearanceforms_appearanceid'), table_name='appearanceforms')
    # ### end Alembic commands ###
