"""init schema

Revision ID: bba8f2c660e1
Revises: 
Create Date: 2026-04-11 13:55:01.139306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba8f2c660e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appearanceformtypes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearancetypes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), nullable=False),
    sa.Column('wikihref', sa.VARCHAR(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), nullable=False),
    sa.Column('wikihref', sa.VARCHAR(length=127), nullable=False),
    sa.Column('season', sa.SMALLINT(), nullable=False),
    sa.Column('number', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearanceformtypealiases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('refid', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=127), nullable=False),
    sa.ForeignKeyConstraint(['refid'], ['appearanceformtypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episodeid', sa.INTEGER(), nullable=False),
    sa.Column('entityid', sa.INTEGER(), nullable=False),
    sa.Column('appearancetypeid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['appearancetypeid'], ['appearancetypes.id'], ),
    sa.ForeignKeyConstraint(['entityid'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['episodeid'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearancetypealiases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('refid', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=127), nullable=False),
    sa.ForeignKeyConstraint(['refid'], ['appearancetypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearanceforms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appearanceid', sa.INTEGER(), nullable=False),
    sa.Column('appearanceformtypeid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['appearanceformtypeid'], ['appearanceformtypes.id'], ),
    sa.ForeignKeyConstraint(['appearanceid'], ['appearances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appearanceforms')
    op.drop_table('appearancetypealiases')
    op.drop_table('appearances')
    op.drop_table('appearanceformtypealiases')
    op.drop_table('episodes')
    op.drop_table('entities')
    op.drop_table('appearancetypes')
    op.drop_table('appearanceformtypes')
    # ### end Alembic commands ###
