"""add unique constraint to appearanceforms

Revision ID: c0b490324ba8
Revises: 2154b81807c9
Create Date: 2026-04-16 01:22:31.616345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b490324ba8'
down_revision: Union[str, Sequence[str], None] = '2154b81807c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_appearanceforms_appearanceid_appearanceformtypeid'), 'appearanceforms', ['appearanceid', 'appearanceformtypeid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_appearanceforms_appearanceid_appearanceformtypeid'), 'appearanceforms', type_='unique')
    # ### end Alembic commands ###
