name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main
    paths:
      - backend/
      - '!backend/**/*.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: backend/
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ vars.GHCR_BACKEND_IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE -f Dockerfile.api .
          docker push $IMAGE

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        run: |
          az extension add --name containerapp --yes
          az containerapp update \
            --name ${{ vars.AZURE_CONTAINERAPP_NAME }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
            --image $IMAGE \
            --set-env-vars \
              DATABASE_HOST=${{ vars.BACKEND_DATABASE_HOST }} \
              DATABASE_PORT=${{ vars.BACKEND_DATABASE_PORT }} \
              DATABASE_NAME=${{ vars.BACKEND_DATABASE_NAME }} \
              DATABASE_USERNAME=${{ secrets.BACKEND_DATABASE_USERNAME }} \
              DATABASE_PASSWORD=secretref:${{ vars.AZURE_SECRET_DATABASE_PASSWORD_NAME }} \
              REDIS_HOST=${{ vars.BACKEND_REDIS_HOST }} \
              REDIS_PORT=${{ vars.BACKEND_REDIS_PORT }} \
              REDIS_NAME=${{ vars.BACKEND_REDIS_NAME }} \
              REDIS_USERNAME=${{ secrets.BACKEND_REDIS_USERNAME }} \
              REDIS_PASSWORD=${{ secrets.BACKEND_REDIS_PASSWORD }}
