name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.41.7

      - name: Create .env file
        run: |
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build models
        run: dart run build_runner build

      - name: Build i10n
        run: flutter gen-l10n

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
